CREATE TABLE EMPLEADOS (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    SALARIO NUMBER(10, 2) CHECK (SALARIO >= 0)
);

INSERT INTO EMPLEADOS (ID, NOMBRE, APELLIDO, SALARIO)
VALUES (101, 'Carlos', 'Gomez', 20000);

COMMIT;